#---------------------------------#
#      General configuration      #
#---------------------------------#

image: Visual Studio 2017

version: 0.1.0

branches:
  only:
    - master
    - develop

configuration:
- Debug
- Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.{build}'
  assembly_file_version: '{version}.{build}'

environment:
  COVERALLS_REPO_TOKEN:
    secure: ZM3cfILSeJIYHKAvV+/wa5Smu9spteVYfCGlreP6jXRKRryNL8rqwXDKrUD+KnMc    

#---------------------------------#
#       Build configuration       #
#---------------------------------#

before_build:
  - cmd: nuget restore .\Source\WbTstr.sln

build:
  project: .\Source\WbTstr.sln
  publish_nuget: true
  verbosity: minimal

after_build:
  - ps: .\Scripts\AppVeyor\after_build.ps1

test_script:
  - ps: .\Scripts\AppVeyor\test_script.ps1

artifacts:
  - path: '**\WbTstr.{version}.nupkg'
    