#---------------------------------#
#      General configuration      #
#---------------------------------#

image: Visual Studio 2015

version: 0.0.0.{build}

branches:
  only:
    - master
    - develop

#---------------------------------#
#       Build configuration       #
#---------------------------------#

before_build:
- cmd: nuget restore Source\WbTstr.sln

build:
  project: Source\WbTstr.sln
  verbosity: minimal
